sudo: required

language: perl

matrix:
    include:
        # - perl: "5.26"

        # - perl: "5.24"
          # - perl: "5.24"
          # addons:
          # mariadb: 5.5
          # - perl: "5.24"
          # addons:
          # mariadb: 10.0
          # - perl: "5.24"
          # addons:
          # mariadb: 10.1
        - perl: "5.24"
          env: MYSQL_VERSION=5.7

          # - perl: "5.22"
          # - perl: "5.20"
          # - perl: "5.18"
          # - perl: "5.16"
          # - perl: "5.14"
          # - perl: "5.12"
          # - perl: "5.10"

before_install:
    - if [ x"$MYSQL_VERSION" != "x" ];
      then
        sudo service mysql stop;
        sudo aptitude purge -y mysql-server libmysqlclient-dev mysql-server-5.6 mysql-common-5.6 mysql-client-5.6 libmysqlclient18 mysql-client-core-5.6 mysql-server-core-5.6 libdbd-mysql-perl mysql-common;
        sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5;
        . /etc/lsb-release;
        sudo add-apt-repository "deb http://repo.mysql.com/apt/ubuntu/ $DISTRIB_CODENAME mysql-$MYSQL_VERSION";
        sudo apt-get update;
        sudo DEBIAN_FRONTEND=noninteractive apt-get -q --yes --fix-broken --allow-unauthenticated --option DPkg::Options::=--force-confnew install mysql-server libmysqlclient-dev;
        sudo mysql_upgrade -u root --password='' --force;
        sudo service mysql restart;
      fi

install:
    - if [ "$TRAVIS_MARIADB_VERSION" ] ; then sudo aptitude install -y libmariadbclient-dev; fi
    - sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
    - mysql -u root --password='' -e 'show databases;'
    - cpanm Data::Dumper
    - dzil authordeps --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - cpanm Devel::Cover Devel::Cover::Report::Coveralls Dist::Zilla::App::Command::cover || { cat ~/.cpanm/build.log ; false ; }

script:
    - sudo mysql -u root --password='' -e 'show databases;'
    - sudo mysql -u root --password='' -e 'drop database if exists test;'
    - perl -Ilib t/Minion-Backend-mysql.t
    - dzil test --author --release
    - RELEASE_TESTING=1 AUTHOR_TESTING=1 dzil cover -report coveralls
