sudo: required

language: perl

matrix:
    include:
        # - perl: "5.26"

        # - perl: "5.24"
          # - perl: "5.24"
          # addons:
          # mariadb: 5.5
          # - perl: "5.24"
          # addons:
          # mariadb: 10.0
          # - perl: "5.24"
          # addons:
          # mariadb: 10.1
        - perl: "5.24"
          env: MYSQL_VERSION=8.0

          # - perl: "5.22"
          # - perl: "5.20"
          # - perl: "5.18"
          # - perl: "5.16"
          # - perl: "5.14"
          # - perl: "5.12"
          # - perl: "5.10"

before_install:
    - if [ x"$MYSQL_VERSION" != "x" ];
      then
        sudo service mysql stop;
        sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5;
        . /etc/lsb-release;
        sudo add-apt-repository "deb http://repo.mysql.com/apt/ubuntu/ $DISTRIB_CODENAME mysql-$MYSQL_VERSION";
        sudo apt-get update;
        sudo DEBIAN_FRONTEND=noninteractive apt-get -q --yes --fix-broken --allow-unauthenticated --option DPkg::Options::=--force-confnew install mysql-server;
        echo "upgrading mysql";
        sudo mysql_upgrade -u root --password='' --force;
        sudo service mysql restart;
      fi

matrix:
    include:
        - perl: "5.26"
          env: COVERAGE=1

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR

install:
    - sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
    - if [ "$TRAVIS_MARIADB_VERSION" ] ; then sudo aptitude install -y libmariadbclient-dev; fi
    - cpan-install --deps
    - cpan-install --coverage

before_script:
    - coverage-setup

script:
    - perl Makefile.PL
    - make
    - prove -bl -s -j$(test-jobs) $(test-files)

after_success:
    - coverage-report
